name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 14
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          xo: true
      - name: Run tests
        run: npm run test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build package
        run: npm run build
      # - name: Publish package
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
